apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devtrack
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'devtrack-backend'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['devtrack-backend-service:8000']
