apiVersion: v1
kind: ConfigMap
metadata:
  name: devtrack-config
  namespace: devtrack
data:
  POSTGRES_HOST: "devtrack-postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "devtrack"
  APP_ENV: "production"
  REACT_APP_API_URL: ""
