apiVersion: v1
kind: Secret
metadata:
  name: devtrack-secret
  namespace: devtrack
type: Opaque
stringData:
  POSTGRES_USER: "devtrack_user"
  POSTGRES_PASSWORD: "devtrack_secure_password_2026"
  DATABASE_URL: "postgresql://devtrack_user:devtrack_secure_password_2026@devtrack-postgres-service:5432/devtrack"
