apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devtrack-backend-hpa
  namespace: devtrack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devtrack-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
